export const strings = {
  settings: {
    title: 'Настройки',
    currencySection: '💱 Выбор валюты',
    currentCurrency: 'Текущая валюта:',
    appInfoSection: 'О приложении',
    systemSection: '⚙️ Система',
    dangerZoneSection: '⚠️ При необходимости',
    version: 'Версия приложения',
    totalTransactions: 'Всего операций',
    storageType: 'Тип хранилища',
    theme: 'Текущая тема',
    deleteAllData: 'Удалить все данные',
    deleteAllTitle: '⚠️ Удалить все данные?',
    deleteAllMessage: 'Это действие нельзя отменить. Все ваши транзакции будут удалены.',
    cancel: 'Отмена',
    delete: 'Удалить все',
    success: 'Есть!',
    successMessage: 'Все данные удалены',
    loading: 'Загрузка настроек...',
  },
  home: {
    title: 'Домашняя страница',
    balance: 'Баланс',
    income: 'Доход',
    expense: 'Расход',
    noTransactions: 'Нет транзакций',
    addFirstTransaction: 'Добавьте первую операцию',
    loading: 'Загрузка...',
  },
  addTransaction: {
    title: 'Добавить операцию',
    transactionType: 'Тип операции',
    expense: '📉 Расход',
    income: '📈 Доход',
    amount: 'Сумма',
    category: 'Категория',
    description: 'Описание (необязательно)',
    addButton: 'Добавить транзакцию',
    backButton: '← Вернуться',
    errorAmount: 'Введите корректную сумму',
    errorCategory: 'Выберите категорию',
    success: 'Есть!',
    successMessage: 'Транзакция добавлена',
    error: 'Ошибка',
  },
  statistics: {
    title: 'Статистика',
    generalStats: '📊 Общая статистика',
    totalBalance: 'Общий баланс',
    income: 'Общий доход',
    expense: 'Общие расходы',
    byCategories: '📋 По категориям',
    noData: 'Пока нет данных',
  },
};
